source "https://www.rubygems.org"

gem "sinatra"
gem "sinatra-contrib"
gem "mustache"
gem "activerecord"
gem "pry"
gem "pg"
gem "sinatra-flash"
gem "will_paginate"
gem "redcarpet"
gem "will_paginate/active_record"
gem "twilio-ruby"
gem "sendgrid-ruby"